variable "resource-group-name" {}
variable "vnet-name" {}
variable "location" {}
variable "Nat-SB-name" {}
variable "Nat-SB-address_prefixes" {}
variable "NAT-pip-name" {}
variable "NAT-pip-allocation_method" {}
variable "NAT-pip-sku" {}
variable "NAT-GWY-name" {}
variable "NAT-GWY-sku_name" {}
