variable "pip-name" {}
variable "pip-allocation_method" {}
variable "LB-name" {}
variable "LB-FEIP-name" {}
variable "BEPool-name" {}
variable "LBProbe-name" {}
variable "LBprobe-port" {}
variable "LBRule-name" {}
variable "LBRule-protocol" {}
variable "LBRule-frontend-port" {}
variable "LBRule-backend-port" {}
variable "NSG-name" {}
variable "resource-group-name" {}
variable "location" {}
